---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
  index.html: |
    <html>
    <head><title>Welcome to Nginx</title></head>
    <body>
    <h1>Hello from Nginx running in Minikube!</h1>
    </body>
    </html>
